name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  dartz: ^0.10.1
  equatable: ^2.0.2
  google_fonts: ^2.1.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  test_cov_console: ^0.2.2
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.1
  flutter:
    sdk: flutter

#modularization
  about:
    path: ../about
  movie:
    path: ../movie
  tv_series:
    path: ../tv_series
  search:
    path: ../search
  watchlist:
    path: ../watchlist

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.7
  analyzer: ^2.6.0
  mocktail: ^0.2.0
  bloc_test: ^9.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         styles: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
